In [1]:
import numpy as np
import pandas as pd

In [2]:
num=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])# 2X4 matrix 2 rows and 4 column
print(num)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]


In [3]:
df = pd.DataFrame(num)
print(df)

    0   1   2   3
0   1   2   3   4
1   6   7   8   9
2  10  11  12  13


In [4]:
df = pd.DataFrame(num, columns=['A','B','C','D'])
print(df)

    A   B   C   D
0   1   2   3   4
1   6   7   8   9
2  10  11  12  13


In [5]:
df['E'] = [10,11,12] # adding new column
print(df)

    A   B   C   D   E
0   1   2   3   4  10
1   6   7   8   9  11
2  10  11  12  13  12


In [6]:
Packet= pd.read_csv(r"C:\Users\yashs\OneDrive\Desktop\ML\datasetML\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yashs\\OneDrive\\Desktop\\ML\\datasetML\\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX'

In [9]:

pip install scapy pyshark

Note: you may need to restart the kernel to use updated packages.
